name: Zot Chart Build and Push

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*']

jobs:
  helm-build-push:
    name: helm-build-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Setup Oras
        uses: oras-project/setup-oras@v1
        with:
          version: 1.2.0

      - name: Helm Lint
        run: |
          just helm-lint

      - name: Helm Package
        run: |
          just helm-package

      - name: Login to ghcr.io
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Oras Push
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          just push-chart

